version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1716537822
layout:
  navigation: {  }
  /header/:
    -
      - owlcarousel-2455
  /intro/:
    -
      - 2cols_w_image-5354
  /pricing/:
    -
      - pricing-5306
  /features/:
    -
      - contentcubes-6469
  /testimonials/:
    -
      - testimonials_carousel-4183
  /utility1/:
    -
      - custom-9685
  /info/:
    -
      - content_repeater-7607
  /utility2/:
    -
      - custom-9485
  /above/: {  }
  /container-main/:
    -
      -
        'mainbar 75': {  }
      -
        'sidebar 25': {  }
  expanded:
    -
      - contenttabs-3854
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: 'g-flushed min-h-75'
      variations: ''
  intro:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  pricing:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  features:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  utility1:
    type: section
    attributes:
      boxed: ''
      class: g-flushed
      variations: ''
  info:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  utility2:
    type: section
    attributes:
      boxed: ''
      class: g-flushed
      variations: ''
  above:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      nav: enable
      imageOverlay: disable
      items:
        -
          class: ''
          image: 'gantry-media://owlcarousel/slide_01.jpg'
          line1: 'Dein Haustier verdient seinen eigenen'
          line2: 'Walk of Fame'
          link: '#g-contenttabs-contenttabs-3854'
          linktext: 'Frag mich mal'
          disable: '0'
          name: 'Item 1'
        -
          class: ''
          image: 'gantry-media://owlcarousel/slide_02.jpg'
          line1: 'Dein Haustier verdient seinen eigenen'
          line2: 'Walk of Fame'
          link: '#g-contenttabs-contenttabs-3854'
          linktext: 'Frag mich mal'
          disable: '0'
          name: 'Item 2'
        -
          class: ''
          image: 'gantry-media://owlcarousel/slide_03.jpg'
          line1: 'Dein Haustier verdient seinen eigenen'
          line2: 'Walk of Fame'
          link: '#g-contenttabs-contenttabs-3854'
          linktext: 'Frag mich mal'
          disable: '0'
          name: 'Item 3'
        -
          class: ''
          image: 'gantry-media://owlcarousel/slide_04.jpg'
          line1: 'Dein Haustier verdient seinen eigenen'
          line2: 'Walk of Fame'
          link: '#g-contenttabs-contenttabs-3854'
          linktext: 'Frag mich mal'
          disable: '0'
          name: 'Item 4'
        -
          class: ''
          image: 'gantry-media://owlcarousel/slide_05.jpg'
          line1: 'Dein Haustier verdient seinen eigenen'
          line2: 'Walk of Fame'
          link: '#g-contenttabs-contenttabs-3854'
          linktext: 'Frag mich mal'
          disable: '0'
          name: 'Item 5'
  2cols_w_image-5354:
    title: 'Two cols w/image'
    attributes:
      image: 'gantry-media://mics/da-bin-ich.png'
      link: /da-bin-ich
      linktext: 'Da bin ich'
      description: "Willkommen in meiner kreativen Welt, in der dein Liebling zum Star wird!\nHi, ich bin Julia - Tierfotografin mit der innigen Liebe zum kreativen Bild und Hundefachfrau.\nFr√∂hliche und bunte Fotoshootings mit den unterschiedlichsten Haustieren sind mein Markenzeichen. Als ausgebildete Hundefachfrau habe ich ein besonderes Augenmerk auf das Wohlbefinden, die Sicherheit und die individuellen Bed√ºrfnisse deines geliebten Hundes.\LEuer Wohlbefinden, der Spa√ü w√§hrend des Shootings, stressfreie Fotoshootings und die Freude an den entstandenen Bildern haben f√ºr mich oberste Priorit√§t. F√ºr die einzigartigen Kulissen und Requisiten scheue ich keine Kosten und M√ºhen und habe stets etwas neues im Repertoire. Dein exklusives Fotoshooting kannst du direkt in meinem Fotostudio in Werdohl oder auch, dank meines mobilen Fotostudios, an jedem Ort in Nordrhein-Westfalen genie√üen. Gern auch direkt bei dir zu Hause, in den eigenen vertrauten W√§nden."
  pricing-5306:
    attributes:
      link: /kann-sein
      linktext: 'Was kostet'
      prices:
        -
          image: 'gantry-media://pricing/studio.png'
          description: 'Spare dir und deinem geliebten Vierbeiner die Anfahrt zu mir und genie√üe ein Fotoshooting direkt bei dir zu Hause. Mit meinem mobilen Fotostudio holst du die Magie der kreativen Studiofotografie in deine eigenen vier W√§nde, wo wir in entspannter Atmosph√§re unvergessliche Bilder zaubern.'
          amount: '200'
          id: ''
          class: ''
          variations: ''
          title: 'Mobiles Studio'
        -
          image: 'gantry-media://pricing/momente.png'
          description: 'Du kannst frei w√§hlen, ob du in meinem Fotostudio in Werdohl oder drau√üen in der wundersch√∂nen Natur, authentische und lebendige Momentaufnahmen deines geliebten Tieres einfangen lassen m√∂chtest. Ungestellt und fr√∂hlich, im gr√ºnen Gras, beim Lieblingsspiel oder beim kuscheln.'
          amount: '150'
          id: ''
          class: ''
          variations: ''
          title: 'Studio oder Outdoor'
        -
          image: 'gantry-media://pricing/reportage.png'
          description: 'Bei der Begleitung deines Events halte ich die Highlights und die unbezahlbaren und seltenen Momente fest, damit du dich auch in viele Jahren noch an diesen besonderen Anlass erinnern kannst. W√§hrend du dich voll auf deine Fellnase konzentrierst √ºbernehme ich den Rest.'
          amount: '200'
          id: ''
          class: ''
          variations: ''
          title: 'Reportage Fotografie'
  contentcubes-6469:
    title: 'Content Cubes'
    attributes:
      css:
        class: ''
      title: Erfolg
      link: /erfolg
      items:
        -
          thumbnail: 'gantry-media://features/theater-machen-400x386.jpg'
          image: 'gantry-media://features/theater-machen.jpg'
          imageposition: left
          desc: 'Hier finden Sie eine Welt voller Emotionen, die in Momenten des Theaterspiels, der Lebensfreude und unerwarteten Momenten festgehalten werden. Jedes Bild erz√§hlt seine eigene Geschichte, die mit dem Objektiv meiner Kamera aufgenommen wurde, und spiegelt die einzigartige Pers√∂nlichkeit und Sch√∂nheit unserer Begleittiere wider.'
          images:
            -
              thumbnail: 'gantry-media://features/erfolg-01-300x199.jpg'
              image: 'gantry-media://features/erfolg-01.jpg'
              alttext: Kanninchen
              text: 'New item'
            -
              thumbnail: 'gantry-media://features/erfolg-02-300x233.jpg'
              image: 'gantry-media://features/erfolg-02.jpg'
              text: 'New item'
            -
              thumbnail: 'gantry-media://features/erfolg-03-303x400.jpg'
              image: 'gantry-media://features/erfolg-03.jpg'
              text: 'New item'
          name: 'Theater machen'
        -
          thumbnail: 'gantry-media://features/lebhafte-400x265.jpg'
          image: 'gantry-media://features/lebhafte.jpg'
          imageposition: right
          desc: ''
          images:
            -
              thumbnail: 'gantry-media://features/erfolg-04-300x198.jpg'
              image: 'gantry-media://features/erfolg-04.jpg'
              alttext: ''
              text: 'New item'
            -
              thumbnail: 'gantry-media://features/erfolg-05-300x216.jpg'
              image: 'gantry-media://features/erfolg-05.jpg'
              alttext: ''
              text: 'New item'
          name: Lebhafte
        -
          thumbnail: 'gantry-media://features/erwischt-400x400.jpg'
          image: 'gantry-media://features/erwischt.jpg'
          imageposition: left
          desc: ''
          images:
            -
              thumbnail: 'gantry-media://features/erfolg-06-269x400.jpg'
              image: 'gantry-media://features/erfolg-06.jpg'
              alttext: ''
              text: 'New item'
            -
              thumbnail: 'gantry-media://features/erfolg-07-300x200.jpg'
              image: 'gantry-media://features/erfolg-07.jpg'
              alttext: ''
              text: 'New item'
          name: Erwischt
  testimonials_carousel-4183:
    title: 'Testimonials Carousel'
    attributes:
      title: 'Man √ºber mich'
      link: /da-bin-ich
      nav: enable
      imageOverlay: disable
      items:
        -
          class: ''
          image: 'gantry-media://testimonials/testimonial1.jpg'
          date: 10.02.2024
          desc: '√úberw√§ltigt von der Hundefotografin Julia: Ihre Bilder sind wahre Kunst, die Seelen meiner zwei Hunde und meines Katers einfangen. Mit Talent, Leidenschaft und einem Auge f√ºrs Detail macht sie jede Session einzigartig. Unvergessliche Erinnerungen, absolut empfehlenswert!'
          link: 'https://www.instagram.com/kinolog.lapki.nrw'
          linktext: '@kinolog.lapki.nrw'
          disable: '0'
          name: 'Olesya Poruchnyk'
        -
          class: ''
          image: 'gantry-media://testimonials/testimonial2.jpg'
          date: 17.10.2023
          desc: 'Hallo, danke f√ºr unsere Fotos mit Lunochka üòç Die Aufnahmen sind so lebendig geworden, mir hat alles sehr gefallen, man sieht, dass es Ihnen viel Freude bereitet und man sp√ºrt neben Ihrem Professionalismus auch eine gro√üe Liebe zu Tieren ‚ò∫Ô∏è Ich erinnere mich, wie Sie damals noch mit einem Gips am Bein gearbeitet haben, aber das hat Sie nicht davon abgehalten, die sch√∂nsten und erfolgreichsten Aufnahmen von Luna und den anderen Hunden zu machen üôàüòç Ich bewundere Ihren Beruf, Sie machen Hundebesitzer gl√ºcklicher ü•∞ Ich w√ºnsche Ihnen mehr Ideen und mehr M√∂glichkeiten zu deren Umsetzung üôèüèª‚ò∫Ô∏è'
          link: 'https://www.instagram.com/promama_lera'
          linktext: '@promama_lera'
          disable: '0'
          name: promama_lera
        -
          class: ''
          image: 'gantry-media://testimonials/testimonial3.jpg'
          date: 28.03.2024
          desc: 'Liebe Julia hat uns heute besucht! Sie kam zu uns nach Hause und machte Fotos mit meinen Kaninchen. Zuerst hat sie alle ihre Sachen f√ºr das Shooting mitgebracht und dann haben wir alles an seinen Platz gebracht. Es ist sehr lustig, wie viele interessante Dinge sie dabei hatte. Unterschiedliche Hintergr√ºnde und allerlei Kleinigkeiten. Wir haben verschiedene Motive ausprobiert, es war toll, die Kaninchen spielten die Hauptrolle und es hat sogar Spa√ü gemacht. Sehr einf√ºhlsame und nette Fotografin! Wir freuen uns darauf, Julia wiederzusehen!'
          link: 'https://www.instagram.com/vomhoennetal'
          linktext: '@vomhoennetal'
          disable: '0'
          name: vomhoennetal
        -
          class: ''
          image: 'gantry-media://testimonials/testimonial4.jpg'
          date: 29.09.2024
          desc: 'Ich bin absolut begeistert von der Hundefotografin Julia, die schon seit einiger Zeit die besonderen Momente unserer vierbeinigen Freunde festh√§lt. Ihre Arbeit ist einfach beeindruckend und hat mir pers√∂nlich sehr geholfen. Die Fotos, die sie macht, sind mehr als nur Bilder ‚Äì sie sind echte Kunstwerke, die Pers√∂nlichkeit und die einzigartigen Charakterz√ºge jedes Hundes einfangen. Besonders w√§hrend der Gruppenstunden in unserer Hundeschule Lapki in Mettmann beweist sie immer wieder aufs Neue ihr au√üergew√∂hnliches Talent und Gesp√ºr f√ºr den richtigen Moment. Jedes Mal, wenn sie bei uns ist, freue ich mich schon auf die wunderbaren Fotos, die entstehen. Sie hat nicht nur ein gutes Auge f√ºr die besonderen Momente, sondern versteht es auch, eine entspannte Atmosph√§re zu schaffen, in der sich sowohl Hunde...'
          link: 'https://lapki.nrw'
          linktext: 'Hundeschule Lapki'
          disable: '0'
          name: 'Hundeschule Lapki'
  custom-9685:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"g-grid\">\n\t<div class=\"g-block ticket\">\n\t\t<div class=\"g-content center p-2\">\n\t\t\t<div class=\"heading heading-2xlarge\">100%</div>\n\t\t\t<div class=\"heading heading-large\">Rabatt</div>\n\t\t</div>\n\t</div>\n\t<div class=\"g-block d-flex align-items-center\">\n\t\t<div class=\"g-content p-2\">\n\t\t\t<div class=\"heading heading-medium mb-2\">Ein beliebiges Fotoshooting f√ºr Dein aus dem Tierheim adoptiertes Tier</div>\n\t\t<a href=\"#g-contenttabs-contenttabs-3854\" class=\"button\">Frag mich mal</a>\n\t\t</div>\n\t</div>\n</div>"
  content_repeater-7607:
    title: 'Content repeater'
    attributes:
      title: Tierheimhilfe
      link: /tierheimhilfe
      content:
        -
          class: ''
          name: ''
          thumbnail: 'gantry-media://mics/tierheimhilfe.png'
          image: 'gantry-media://mics/tierheimhilfe.jpg'
          imagealt: Tierheimhilfe
          date: ''
          desc: 'Ich finde es wichtig, mein Herz und meine F√§higkeiten f√ºr einen guten Zweck einzusetzen. Deshalb verbringe ich auch Zeit als Freiwilliger in Tierheimen ‚Äì fotografiere die Sch√ºtzlinge, spiele mit den Katzen, gehe mit den Hunden spazieren und reinige die K√§fige. Einen Teil der Einnahmen spende ich ebenfalls an die Tierheime. Meine Kunden entscheiden selbst, welchem Tierheim das Geld zugutekommt. Gemeinsam leisten wir einen Beitrag zur Unterst√ºtzung bed√ºrftiger Tiere.'
          link: /tierheimhilfe
          linktext: 'Mehr sehen'
          disable: '0'
          title: 'New item'
  custom-9485:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"g-grid\">\n\t<div class=\"g-block size-100 center ticket\">\n\t\t<div class=\"g-content\">\n\t\t\t<div class=\"heading heading-xlarge\">50% Rabatt</div>\n\t\t</div>\n\t</div>\n\t<div class=\"g-block size-100\">\n\t\t<div class=\"g-grid\">\n\t\t\t<div class=\"g-block d-flex justify-content-center align-items-center p-2\">\n\t\t\t\t<div class=\"heading heading-medium align-right\">beim Fotoshootings am Geburtstag Deines Tieres</div>\n\t\t\t</div>\n\t\t\t<div class=\"g-block d-flex justify-content-center align-items-center\">\n\t\t\t\t<a href=\"#g-contenttabs-contenttabs-3854\" class=\"button\">Frag mich mal</a>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>"
  contenttabs-3854:
    title: 'Content Tabs'
    attributes:
      title: Kontaktformular
      link: /kontakt
      desc: "<p>M√∂chtest du ein besonderes Fotoshooting organisieren oder einfach mehr erfahren? Erz√§hl mir, wen du auf den Fotos sehen m√∂chtest ‚Äì deine s√º√üen Haustiere und welche genau, alleine oder mit ihren Lieblingsmenschen. Vergiss nicht anzugeben, wo du wohnst und welche Zeit dir am besten passt. Hast du besondere W√ºnsche oder Ideen f√ºr das Thema des Shootings?</p>\n\n<p>Dies ist nur eine Informationsanfrage, die dich zum weiteren nicht verpflichtet. Ich freue mich darauf, mehr √ºber deine W√ºnsche zu erfahren und die Details deiner einzigartigen Fotosession zu besprechen!</p>\n\n<p>* zeigt erforderliche Felder an</p>"
      thumbnail: 'gantry-media://mics/kontaktformular.png'
      image: 'gantry-media://mics/kontaktformular.jpg'
      items:
        -
          content: '[wpforms id="1008"]'
          title: 'Anfrage zur dein Tierfotografin'
        -
          content: '<div>Demn√§chst verf√ºgbar</div>'
          title: 'Anfrage f√ºr dein Fotoshooting'
